#!/usr/bin/env bash
set -ue

OLD_DB_PATH="$1"
NEW_DB_PATH="$2"

OLD_DB_CONTENT_PATH="$(mktemp)"
NEW_DB_CONTENT_PATH="$(mktemp)"

QUERY='select name, type, path from searchIndex;'

sqlite3 -init /dev/null "${OLD_DB_PATH}" "${QUERY}" >"${OLD_DB_CONTENT_PATH}"
sqlite3 -init /dev/null "${NEW_DB_PATH}" "${QUERY}" >"${NEW_DB_CONTENT_PATH}"

DIFF_CMD="diff"

PREFERRED_DIFF_CMDS=("ksdiff")
for CMD in "${PREFERRED_DIFF_CMDS[@]}"; do
	if command -v "${CMD}" >/dev/null; then
		DIFF_CMD="${CMD}"
		break
	fi
done

${DIFF_CMD} "${OLD_DB_CONTENT_PATH}" "${NEW_DB_CONTENT_PATH}"
