#!/usr/bin/env bash
set -ue

OLD_DB_PATH="$1"
NEW_DB_PATH="$2"

OLD_DB_CONTENT_PATH="$(mktemp)"
NEW_DB_CONTENT_PATH="$(mktemp)"

QUERY='SELECT name, type, path FROM searchIndex;'

# Stop the possibility of a user's ~/.sqliterc file setting an unexpected output mode.
SQLITE="sqlite3 -init /dev/null"

${SQLITE} "${OLD_DB_PATH}" "${QUERY}" >"${OLD_DB_CONTENT_PATH}"
${SQLITE} "${NEW_DB_PATH}" "${QUERY}" >"${NEW_DB_CONTENT_PATH}"

DIFF_CMD="diff"

PREFERRED_DIFF_CMDS=("ksdiff")
for CMD in "${PREFERRED_DIFF_CMDS[@]}"; do
	if command -v "${CMD}" >/dev/null; then
		DIFF_CMD="${CMD}"
		break
	fi
done

${DIFF_CMD} "${OLD_DB_CONTENT_PATH}" "${NEW_DB_CONTENT_PATH}"
