#!/usr/bin/env python3

import sqlite3
import sys

_, old_db_path, new_db_path = sys.argv


def getall(db_path):
    db = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    c = db.cursor()
    c.execute("SELECT name, type, path FROM searchIndex")
    result = c.fetchall()
    db.close()
    return result


old_rows = getall(old_db_path)
new_rows = getall(new_db_path)


ref = {}

for row in old_rows:
    ref[row[0]] = row[1:]

old_names = {x[0] for x in old_rows}
new_names = {x[0] for x in new_rows}

missing = old_names - new_names

for row in sorted(missing):
    print(f"missing: {row:15s} -> {ref[row]}")  # noqa: T001
