#!/usr/bin/env python3

import plistlib
import sys

(
    _,
    name,
    readable_name,
    search_keyword,
    main_page,
    online_page_base_url,
    output_path,
) = sys.argv

# REF: https://kapeli.com/docsets (search for "Info.plist")

info = {
    "CFBundleIdentifier": name,
    "CFBundleName": readable_name,
    # If the search keyword is already well-known to Dash, it will also be used to assign the docset's icon.
    "DocSetPlatformFamily": search_keyword,
    "isDashDocset": True,
    "dashIndexFilePath": main_page,
    "DashDocSetFamily": "dashtoc",
    "DashDocSetFallbackURL": online_page_base_url,
    # @todo Is opting in to Dash's new Full-Text-Search worth it? Might clutter results for not much gain.
    # @body https://blog.kapeli.com/dash-6
    # "DashDocSetDefaultFTSEnabled": True,
}

# @todo If the "Open Online Page" feature stops working again (see commit 4df4259), we will need to resort to the more laborious approach of embedding special comments in every HTML file.
# @body https://kapeli.com/docsets#onlineRedirection
# @body That would need to happen for every single HTML file in the manual, not just the Module and Library pages that we have "handle_" functions for.

with open(output_path, "wb") as f:
    plistlib.dump(info, f)
